import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';
import { PMTiles, TileType } from 'pmtiles';
import { ArrayBufferSource } from './pmtilesSource.js';

// Integration: the REAL pmtiles reader over our ArrayBufferSource, against
// the committed fixture archive (generated by scripts/make-fixture-pmtiles.mjs
// — a hand-encoded, uncompressed, single-tile PMTiles v3 so tests never need
// the Go CLI or the user's real extract). Node 20 has DecompressionStream,
// so nothing here needs a browser.
const FIXTURE_PATH = fileURLToPath(
  new URL('../../e2e/fixtures/test-basemap.pmtiles', import.meta.url),
);

async function openFixture() {
  const bytes = await readFile(FIXTURE_PATH);
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  return new PMTiles(new ArrayBufferSource(buffer, 'fixture'));
}

describe('fixture archive through the real PMTiles reader', () => {
  test('getHeader reports an MVT archive with the expected zooms and bounds', async () => {
    const header = await (await openFixture()).getHeader();

    expect(header.tileType).toBe(TileType.Mvt);
    expect(header.minZoom).toBe(0);
    expect(header.maxZoom).toBe(0);
    // Bounds must include the e2e's faked London position (51.5, -0.14).
    expect(header.minLon).toBeLessThan(-0.14);
    expect(header.maxLon).toBeGreaterThan(-0.14);
    expect(header.minLat).toBeLessThan(51.5);
    expect(header.maxLat).toBeGreaterThan(51.5);
  });

  test('getZxy(0,0,0) returns the tile bytes', async () => {
    const tile = await (await openFixture()).getZxy(0, 0, 0);

    expect(tile).toBeTruthy();
    expect(tile.data.byteLength).toBeGreaterThan(0);
  });

  test('a zoom outside the archive range returns nothing rather than throwing', async () => {
    const tile = await (await openFixture()).getZxy(1, 0, 0);
    expect(tile?.data ?? undefined).toBeUndefined();
  });
});
